version: '3.3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "4040:88"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/config/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - pimcorenet

    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        command: --init-file /data/application/init.sql
        volumes:
            - ./docker/mysql_init.sql:/data/application/init.sql
            - ./data/mysql:/var/lib/mysql
            - .:/var/www/html
        environment:
            MYSQL_ROOT_PASSWORD: pimcore
            MYSQL_DATABASE: pimcore
            MYSQL_USER: pimcore
            MYSQL_PASSWORD: pimcore
        networks:
            - pimcorenet

    php:
        build: ./docker/php
        volumes:
            - .:/var/www/html
            - ./docker/php/installpimcore.sh:/var/www/html/installpimcore.sh
        links:
            - mysql:mysql
        depends_on:
            - mysql
        networks:
          - pimcorenet

networks:
    pimcorenet: